version: "3.9"
services:
  mongodb:
    image: mysql
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
