version: "3.9"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=password"
    volumes: db-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8999:8080
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  db-data:
    driver: local
