version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: elasticsearch
    networks:
      - elastic-net
    ports:
      - 9200:9200
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    image: kibana:8.7.0
    container_name: kibana
    networks:
      - elastic-net
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
networks:
  elastic-net:
    driver: bridge
volumes:
  elastic-data:
    driver: local
