version: "3.9"

services:
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    networks:
      - elastic-net
    ports:
      - "9200:9200"
  kibana:
    image: kibana
    container_name: kibana
    networks:
      - elastic-net
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  logstash:
    image: logstash
    container_name: logstash
    networks:
      - elastic-net
    ports:
      - "5044:5044"
    expose:
      - 5044
    depends_on:
      - elasticsearch
networks:
  elastic-net:
    driver: bridge
