# build stage
FROM golang:1.22-bookworm AS build

WORKDIR /app

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY ./ ./

RUN go build -o ./app ./cmd/workersinsights/main.go

# deploy stage
FROM gcr.io/google.com/cloudsdktool/cloud-sdk:slim AS deploy

WORKDIR /

COPY --from=build ./app/app ./app

CMD ./app
