# FL0 Dockerfile
ARG APP_NAME=app
ARG APP_ENV=staging

# build stage
FROM golang:1.21-bookworm AS build

ARG APP_NAME
ENV APP_NAME=$APP_NAME
ARG APP_ENV
ENV APP_ENV=$APP_ENV

WORKDIR /app

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY ./ ./

RUN go build -o ./$APP_NAME ./cmd/workersinsights/main.go

# deploy stage
FROM golang:1.21-alpine as production

ARG APP_NAME
ENV APP_NAME=$APP_NAME
ARG APP_ENV
ENV APP_ENV=$APP_ENV

WORKDIR /root/

COPY --from=build ./$APP_NAME ./
CMD ./$APP_NAME
