# build stage
FROM golang:1.22 AS build

WORKDIR /app

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY *.go ./

RUN go build -o ./app ./cmd/workersinsights/main.go

# deploy stage
FROM golang:1.21-alpine

WORKDIR /app

COPY --from=build ./app ./

EXPOSE 8080

ENTRYPOINT ["./app"]
