# build stage
FROM golang:1.21-bookworm AS build

WORKDIR /app

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY *.go ./

RUN go build -o ./app ./cmd/workersinsights/main.go

# deploy stage
FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=build ./app ./

EXPOSE 8080

# distroless specific instruction
USER nonroot:nonroot

ENTRYPOINT ["./app"]
