version: "3.9"
services:
  mongodb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - "MYSQL_DATABASE=db"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - db-data:/var/lib/mysql
    # expose:
    #   - 3306
volumes:
  db-data:
    driver: local
